# Generated by Django 4.2.4 on 2023-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('SR', 'Solar'), ('WD', 'Wind'), ('HY', 'Hydro'), ('GT', 'Geothermal'), ('BG', 'Bio-gas'), ('BF', 'Bio-fuel')], default='SR', max_length=2)),
                ('hot_prices', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['hot_prices'],
            },
        ),
        migrations.CreateModel(
            name='Hormone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Overdrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
