# Generated by Django 4.2.4 on 2023-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hormone_description_hormone_energy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extend',
            name='source',
            field=models.CharField(choices=[('SOLAR', 'Solar'), ('WIND', 'Wind'), ('HYDRO', 'Hydro'), ('GEOTHERMAL', 'Geothermal'), ('BIO-GAS', 'Bio-gas'), ('BIO-FUEL', 'Bio-fuel')], default='SOLAR', max_length=50),
        ),
    ]
