# Generated by Django 4.2.4 on 2024-01-25 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hormone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hormoneproducer',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='analytics',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='contributions_to_ecosystem',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='customer_orders',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='management',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='storefront',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='total_tenure',
        ),
        migrations.CreateModel(
            name='RenewableEnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=255)),
                ('HormoneProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hormone.hormoneproducer')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('HormoneProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hormone.hormoneproducer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('HormoneProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hormone.hormoneproducer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('HormoneProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hormone.hormoneproducer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionToEcosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_details', models.TextField()),
                ('HormoneProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hormone.hormoneproducer')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions', models.TextField()),
                ('HormoneProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hormone.hormoneproducer')),
            ],
        ),
    ]
