# Generated by Django 4.2.4 on 2024-01-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hormone', '0002_rename_user_profile_hormoneproducer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewableenergytype',
            old_name='engine_type',
            new_name='get_ingins_type',
        ),
    ]
