# Generated by Django 4.2.4 on 2024-01-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hormone', '0004_remove_hormoneuser_deals_of_the_week_and_more'),
    ]

    operations = [
    ]
