# Generated by Django 4.2.4 on 2024-01-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_overdriveproducer_delete_overdriveuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hormoneproducer',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='HormoneUser',
        ),
        migrations.DeleteModel(
            name='HormoneProducer',
        ),
    ]
